# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_event_gallery_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='img_url',
            field=models.FilePathField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_url',
            field=models.FilePathField(),
        ),
    ]
