# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20160102_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img_url',
            field=models.ImageField(upload_to='events'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img_url',
            field=models.ImageField(upload_to='services'),
        ),
    ]
