# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20160102_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.CharField(max_length=250)),
            ],
        ),
    ]
