# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='img',
            new_name='image',
        ),
    ]
